---
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: columns
    vertical_layout: fill
    self_contained: false 
    lib_dir: libs 
params: 
  state: Ohio
  
---

---
title: `r paste0(params$state, " COVID-19 Dashboard")`
---

```{r setup, include=FALSE, echo=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(plotly)
library(DT)
library(rio)
library(sf)
library(stringr)
library(crosstalk)
library(d3scatter)
library(htmltools)

load("ohio_covid.rda")

# tmp <- counties_covid %>% 
#   filter(state %in% c(params$state)) %>% 
#   mutate(cases_10k = cases/(tpop/10000)) %>% 
#   select(NAMELSAD, st, cases_10k, repvote, geometry) %>% 
#   mutate(text = paste(NAMELSAD, "\n", cases_10k, " cases/10,000", sep=""), 
#          repvote = repvote*100)

tmpSh <- SharedData$new(tmp)

tags$head(tags$title(paste0(params$state, " COVID-19 Map")))
```

```{r, result='asis', echo=FALSE}
## using Hipster Ipsum place-holder text.
con <- curl::curl("https://hipsum.co/api/?type=hipster-centric&sentences=6")
hip <- rjson::fromJSON(readLines(con))
htmltools::p(hip)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A


```{r}
  plot_ly(tmpSh, split = ~ text,  color = ~log(cases_10k),  alpha = 1, 
        hoverinfo="text", hoveron="fill", showlegend=FALSE, height=750) %>% 
  highlight(on = "plotly_hover", off = "plotly_doubleclick")
```



Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
d3scatter(tmpSh, ~repvote, ~log(cases_10k), width="100%")
```

### Chart C

```{r}
tmpSh %>% 
  datatable(extensions="Scroller", class="compact",
            colnames = c("County", "State", "# Cases/10k", "Republican\nVote"), 
            rownames=FALSE, 
            options = list(paging=FALSE, pageLength = 20, scrollY = "350px",
                            columnDefs = list(list(className = 'dt-center', 
                                                   targets = 0:3), 
                                              list(visible=FALSE, targets=c(4,5))))) %>% 
  formatRound(columns = c("repvote", "cases_10k"), digits=c(0,1))
```

